# Generated by Django 2.1.3 on 2018-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(db_column='CODE', max_length=100, primary_key=True, serialize=False)),
                ('claimed', models.IntegerField(db_column='CLAIMED')),
            ],
        ),
    ]
